Criando pagina de detalhes do pacote
TreinaDev/insurance-comparator-app pull request #16
Opened 2022-11-08 22:51 UTC by Izabellyrb

Visitante visualiza detalhes do pacote selecionado.

Co-authored-by: Anyelly Luvizott <any.luvizott@gmail.com>
Co-authored-by: Aline Lisboa <alisboam@gmail.com>

Closes #3

2022-11-09 13:59 UTC, joaorsalmeida reviewed
Começou bem este, já deixei umas observações pra antecipar o review final ;)

2022-11-09 13:59 UTC, joaorsalmeida commented on app/controllers/home_controller.rb
> +    if response.status == 200
Particularmente eu gosto mais de usar o método `success?` do Faraday::Response. Ele engloba outros status possíveis alem do 200 e que também representam sucesso. 

Pra isso seria necessário mudar o mock dos testes de vocês.

2022-11-09 13:59 UTC, joaorsalmeida commented on app/models/insurance.rb
> +  # def self.find(isurance)
Sei que ainda é rascunho mas reforçando que eu prefiro realmente que esteja aqui em um método `find` essa lógica da busca.

O nome do parâmetro do método poderia ser `id` pra ficar igual ao padrão do Rails :)

2022-11-09 13:59 UTC, joaorsalmeida commented on config/routes.rb
> +  get 'show/:id', to: 'home#show', as: 'show'
Pq não usar `resources :insurances` logo?

2022-11-09 22:09 UTC, alisboam commented on app/models/insurance.rb
> +  # def self.find(isurance)
Modificação atendida, João.

2022-11-11 13:57 UTC, joaorsalmeida requested changes
Turma, achei um erro conceitual que passou desapercebido por conta dos mocks.

Façam o ajuste mas podemos falar mais no encontro de hoje.

2022-11-11 13:57 UTC, joaorsalmeida commented on spec/models/insurance_spec.rb
> +      result = Insurance.find(@id)
Temos um problema aqui que na verdade já tinha acontecido antes e passou desapercebido.

Esses `@id` e `@query` estão ficando sempre nulos tanto aqui quanto dentro do código dos métodos nos models.

No teste vocês não devem usar `@id` e sim uma variável simples `id` que precisa ter um valor.

Então no mock seria algo como `allow(Faraday).to receive(:get).with("http://localhost:4000/api/v1/insurance/1")` e depois no código vocês chamam `Insurance.find(1)`

No teste eu acho interessante usar um valor pré definido pra ter certeza que o valor que foi passado no `find` chegou até o Faraday. E aqui como é um valor qualquer podemos usar o 1 (ou outro numero) fixo.

2022-11-11 13:57 UTC, joaorsalmeida commented on app/models/insurance.rb
>    def self.search(_query)
Esse `_` no começo indica que essa variável nunca foi usada. No código abaixo vcs usam `@query` que nunca foi definida na verdade.

Fiz um teste de debugar o valor da variável durante a execução e está vindo sempre nulo.

Vocês precisam tirar esse `_` aqui do nome do parâmetro e usar essa variável diretamente no Faraday, sem o `@`

2022-11-11 13:57 UTC, joaorsalmeida commented on app/models/insurance.rb
> +    response = Faraday.get("http://localhost:4000/api/v1/insurance/#{@id}")
O mesmo aqui

2022-11-11 20:11 UTC, joaorsalmeida requested changes

2022-11-11 20:11 UTC, joaorsalmeida commented on spec/models/insurance_spec.rb
>        expect(result).to eq []
Como este método busca 1 único item a partir do seu ID, não faz mto sentido devolver um array. Minha sugestão seria devolver `nil`

2022-11-11 20:11 UTC, joaorsalmeida commented on spec/system/search/visitor_views_insurance_details_spec.rb
> +    insurance = []
O método `find` não deveria devolver um array e sim um único objeto.

2022-11-11 20:11 UTC, joaorsalmeida commented on spec/system/search/visitor_views_insurance_details_spec.rb
> +    insurance = []
O mesmo aqui

2022-11-11 20:11 UTC, joaorsalmeida commented on app/views/insurances/show.html.erb
> +    <li class="list-group-item">Nome da Seguradora: <%= @insurance[0].insurance_name %></li>
Não me parece fazer sentido o `show` ter que percorrer um array. O método `find` deveria devolver um objeto diretamente.

2022-11-13 13:55 UTC, joaorsalmeida approved these changes

2022-11-13 14:23 UTC, merged