Cliente compra pacote de seguro a partir de detalhes pacote
TreinaDev/insurance-comparator-app pull request #31
Opened 2022-11-11 21:35 UTC by alisboam

Co-author: Thalis Freitas <ofthalis@gmail.com>

Criação de formulário para aquisição de pacote de seguro

2022-11-15 06:10 UTC, Thalis-Freitas commented on app/controllers/orders_controller.rb
> +      redirect_to @order, notice: t('Seu pedido está em análise pela seguradora')
pendente criar traduções

2022-11-16 18:53 UTC, joaorsalmeida requested changes

2022-11-16 18:53 UTC, joaorsalmeida commented on Gemfile
> +# gem "bootstrap_form"
Se está comentado é melhor remover o Gemfile ;)

2022-11-16 18:53 UTC, joaorsalmeida commented on spec/system/order/user_order_insurance_spec.rb
> +  it 'se estiver autenticado' do
Estes testes só estão passando pq estão acessando a URL com meios de pagamento fakes. O ideal era fazer o mock do método que lista os meios de pagamento disponíveis.

2022-11-16 19:03 UTC, Thalis-Freitas commented on spec/system/order/user_order_insurance_spec.rb
> +  it 'se estiver autenticado' do
João, íamos fazer a compra já com meios de pagamento mas acabamos voltando atrás e optamos por fazer uma compra mais básica inicialmente pra ir incrementando depois, podemos tirar esse select por enquanto e deixar essa parte do pagamento para outra PR?

2022-11-16 19:19 UTC, joaorsalmeida commented on spec/system/order/user_order_insurance_spec.rb
> +  it 'se estiver autenticado' do
CLaro!

2022-11-17 16:05 UTC, merged