inserido arquivo de configuração de api
TreinaDev/insurance-comparator-app pull request #45
Opened 2022-11-16 18:19 UTC by alisboam

Adicionado configuração de arquivo yml de apis

2022-11-16 18:55 UTC, joaorsalmeida requested changes
Podemos unificar as configurações da API de seguros em uma única linha.

2022-11-16 18:55 UTC, joaorsalmeida commented on app/models/insurance.rb
> -    response = Faraday.get("http://localhost:4000/api/v1/insurances/#{query}")
Se vocês estão armazenando no YAML as URLs sem os endpoints para depois concatenar aqui, não entendi pq ter 2 configurações separadas (insurances_api e insurance_api).

2022-11-16 19:02 UTC, alisboam commented on app/models/insurance.rb
> -    response = Faraday.get("http://localhost:4000/api/v1/insurances/#{query}")
Eu separei em insurance_api e insurances_api porque estávamos usando 2 links diferentes de mock, um para cada com retorno diferente.
Insurance_api -> retorna json com uma
unsurances_apis -> retorna array com todas

2022-11-17 23:10 UTC, joaorsalmeida commented on config/apis.yml
> +  insurances_api: https://run.mocky.io/v3/cdfe379d-88f3-4bce-bf7e-dd16b06f5a0a/api/v1
Faltou tirar essa linha né?!

2022-11-17 23:11 UTC, joaorsalmeida commented on spec/models/payment_option_spec.rb
> +      p api_url
Escapou esse `puts` aqui

2022-11-17 23:12 UTC, joaorsalmeida commented on app/models/insurance.rb
> -    response = Faraday.get("http://localhost:4000/api/v1/insurances/#{query}")
Mas então, os mocks nao podem ditar o nosso código a essa altura. Vi que agora parece que já esta correto, vcs precisam unificar a URL em uma só e ela é a base, algo como `api.seguradoras.com.br/v1/api` e depois vcs concatenam o restante do endpoint + parâmetros.

2022-11-17 23:12 UTC, joaorsalmeida reviewed
Ainda tem alguns ajustes pra fazer.

2022-11-17 23:16 UTC, joaorsalmeida approved these changes
Deixei alguns pedidos de ajustes pequenos, bora fazer antes do merge. Mas já deixo pré aprovado pra agilizar vcs.

2022-11-17 23:29 UTC, alisboam commented on app/models/insurance.rb
> -    response = Faraday.get("http://localhost:4000/api/v1/insurances/#{query}")
Ok. Vou conversar com o pessoal pra unificarmos o link. vou fazer as correções abaixo.

2022-11-17 23:32 UTC, merged